pxf-automation github actions

diff --git a/automation/Makefile b/automation/Makefile
--- a/automation/Makefile
+++ b/automation/Makefile
@@ -245,3 +245,23 @@ endif
 .PHONY: pxf_regress
 pxf_regress:
 	$(MAKE) -C pxf_regress
+
+DEB_DIR=../downloads
+DOCKER_DEB_DIR=docker/universe/debs
+GPDB_DEB=$(DEB_DIR)/greenplum-db-6_6.0.0-bionic-dev_amd64.deb
+PXF_DEB=$(DEB_DIR)/greenplum-pxf-6_6.10.1-bionic-dev_amd64.deb
+
+.PHONY: copy-debs
+copy-debs:
+	@if [ ! -f $(GPDB_DEB) ] || [ ! -f $(PXF_DEB) ]; then \
+	  echo "ERROR: Required deb files not found."; \
+	  echo "Actual contents of $(DEB_DIR):"; \
+	  ls -l $(DEB_DIR); \
+	  echo "Please build them using:"; \
+	  echo "  make -C ../package deb-gpdb-bionic"; \
+	  echo "  make -C ../package deb-pxf6-gpdb-bionic"; \
+	  exit 1; \
+	fi
+	mkdir -p $(DOCKER_DEB_DIR)
+	cp $(GPDB_DEB) $(DOCKER_DEB_DIR)/
+	cp $(PXF_DEB) $(DOCKER_DEB_DIR)/
